import{a as m,S as g,i as a}from"./assets/vendor-tnUJPedx.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function l(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=l(t);fetch(t.href,o)}})();const h="48893139-3f2b1b26814d6cd1a5eec55f2",w="https://pixabay.com/api/";async function L(r,e,l){try{const s=await m.get(w,{params:{key:h,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:l}});return{images:s.data.hits,totalHits:s.data.totalHits}}catch(s){throw console.error("Помилка при завантаженні зображень:",s),s}}const b=document.querySelector(".gallery");function v(r){b.innerHTML=r.map(e=>`
        <a class="gallery-item" href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags.split(",")[0]}" loading="lazy"/>
          <div class="info">
            <p>❤️ ${e.likes} Likes</p>
            <p>👁️ ${e.views} Views</p>
            <p>💬 ${e.comments} Comments</p>
            <p>⬇️ ${e.downloads} Downloads</p>
          </div>
        </a>
      `).join(""),new g(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}).refresh()}const S=document.querySelector("#search-form"),q=document.querySelector("#search-input"),u=document.querySelector("#loader"),f=document.querySelector(".gallery"),n=document.querySelector("#load-more");let d="",i=1;const p=40;S.addEventListener("submit",async r=>{if(r.preventDefault(),d=q.value.trim(),!d){a.error({title:"Помилка",message:"Введіть слово для пошуку!"});return}i=1,f.innerHTML="",n.style.display="none",await y()});n.addEventListener("click",async()=>{i++,await y()});async function y(){u.style.display="block";try{const{images:r,totalHits:e}=await L(d,i,p);if(r.length===0){a.warning({message:"No images found. Try another search."});return}v(r),i*p>=e?(n.style.display="none",a.info({message:"We're sorry, but you've reached the end of search results."})):n.style.display="block",$()}catch{a.error({title:"Error",message:"Не вдалося завантажити зображення. Спробуйте ще раз."})}finally{u.style.display="none"}}function $(){const{height:r}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
